scene:
  cameras:
    - name: "top_cam"
      position: [0.5, 0, 1]
      facing: [-90, 0, 0]
      prim_path: "/Robot/TopCamera"
    - name: "side_cam"
      position: [0.5, 0.5, 0.2]
      facing: [0, 0, 90]
      prim_path: "/Robot/SideCamera"
  table:
    max_children: 3
    max_height: 1.5
    min_wh_sum: 2
  target_object:
    categories:
      - can
    moving_time: [0.5, 2.0]
  other_objects:
    n_objects: 0
    categories:
      - apple

camera:
  width: 480
  height: 360
  fps: 50
  focal_length: 2.3
  focus_distance: 400
  horizontal_aperture: 4.6
  clip:
    near: 0.01
    far: 10000
  data_types:
    - rgb
    - semantic_segmentation
    # - depth

lighting:
  temperature: [5000, 7500]
  intensity: [350, 650]
  position:
    x: [-20, 20]
    y: [-20, 20]
    z: [10, 20]