scene:
  cameras:
    - name: "opst_cam"
      position: [1, 0, 0.6]
      rotation: [0, 60, 90]
      # quat: [0.61237244, 0.35355339, 0.35355339, 0.61237244]
      prim_path: "/Robot/OppositeCamera"
    - name: "side_cam"
      position: [0.5, 1, 0.35]
      rotation: [-90, 0, 180]
      # quat: [0, 0, 0.70710678, 0.70710678]
      prim_path: "/Robot/SideCamera"
  containers:
    n_containers: 1
    categories:
      - bowl
  objects:
    n_objects: 1
    prob_rnd_quat: 0.85
    prob_static: 0.5
    moving_time: [0.5, 2.0]
    categories:
      - can

camera:
  width: 480
  height: 360
  fps: 25
  focal_length: 2.3
  focus_distance: 400
  horizontal_aperture: 4.6
  clip:
    near: 0.01
    far: 10000
  data_types:
    - rgb
    - semantic_segmentation
    # - depth

lighting:
  temperature: [5000, 7500]
  intensity: [350, 650]
  position:
    x: [-20, 20]
    y: [-20, 20]
    z: [10, 20]
