scene:
  table:
    max_children: 3
    max_height: 1.5
    min_wh_sum: 2
  object:
    moving_time:
      - 0.5
      - 5

camera:
  width: 640
  height: 480
  fps: 100
  focal_length: 2.3
  focus_distance: 400
  horizontal_aperture: 4.6
  clip:
    near: 0.01
    far: 10000
  data_types:
    - rgb
    - distance_to_image_plane

lighting:
  temperature:
    - 5000
    - 7500
  intensity: 
    - 350
    - 650
  position:
    x:
      - -20
      - 20
    y:
      - -20
      - 20
    z:
      - 10
      - 20