CONST:
  EXP_NAME: null
  N_WORKERS: 8
  POLICY_NAME: "diffusion"

DATASET:
  NAME: "lerobot/hzxie/dynamic_objects"
  PIN_MEMORY: false
  DELTA_TIMESTAMPS:
    observation.image: [-0.1, 0.0]
    observation.state: [-0.1, 0.0]
    observation.environment_state: [-0.1, 0.0]
    action: [-0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]

DIR:
  OUTPUT: "./runs"

WANDB:
  ENABLED: false
  PROJECT: "DynamicVLA"
  ENTITY: "haozhexie"
  MODE: "online"
  RUN_ID: null
  LOG_CODE: true
  SYNC_TENSORBOARD: false

TRAIN:
  N_EPOCHS: 500
  BATCH_SIZE: 64
  LR: 1.0e-4
  EPS: 1.0e-8
  WEIGHT_DECAY: 0
  BETAS: [0.9, 0.999]
  CKPT_SAVE_FREQ: 20
